
export const FETCH_EVENTS_REQUEST = 'FETCH_EVENTS_REQUEST';
export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS';
export const FETCH_EVENTS_FAILURE = 'FETCH_EVENTS_FAILURE';

export const FETCH_EVENT_SAVE_REQUEST = 'FETCH_EVENT_SAVE_REQUEST';
export const FETCH_EVENT_SAVE_SUCCESS = 'FETCH_EVENT_SAVE_SUCCESS';
export const FETCH_EVENT_SAVE_FAILURE = 'FETCH_EVENT_SAVE_FAILURE';
