
// lista de string utilizados para vincular los actions con los mutations

export const FETCH_EVENTS_REQUEST = 'FETCH_EVENTS_REQUEST';
export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS';
export const FETCH_EVENTS_FAILURE = 'FETCH_EVENTS_FAILURE';

export const FETCH_EVENT_SAVE_REQUEST = 'FETCH_EVENT_SAVE_REQUEST';
export const FETCH_EVENT_SAVE_SUCCESS = 'FETCH_EVENT_SAVE_SUCCESS';
export const FETCH_EVENT_SAVE_FAILURE = 'FETCH_EVENT_SAVE_FAILURE';


export const FETCH_KEYWORDS_REQUEST = 'FETCH_KEYWORDS_REQUEST';
export const FETCH_KEYWORDS_SUCCESS = 'FETCH_KEYWORDS_SUCCESS';
export const FETCH_KEYWORDS_FAILURE = 'FETCH_KEYWORDS_FAILURE';

export const FETCH_KEYWORD_SAVE_REQUEST = 'FETCH_KEYWORD_SAVE_REQUEST';
export const FETCH_KEYWORD_SAVE_SUCCESS = 'FETCH_KEYWORD_SAVE_SUCCESS';
export const FETCH_KEYWORD_SAVE_FAILURE = 'FETCH_KEYWORD_SAVE_FAILURE';

export const SET_KEYWORDS = 'SET_KEYWORDS';